services:
  portainer:
    image: "portainer/portainer-ce:${PORTAINER_VERSION}"
    container_name: portainer
    restart: unless-stopped
    ports:
      - "${PORTAINER_PORT}:${PORTAINER_PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - public-services

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - public-services

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - public-services

  mailhog:
    image: "mailhog/mailhog:${MAILHOG_VERSION}"
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "127.0.0.1:${MAILHOG_WEB_PORT}:${MAILHOG_WEB_PORT}" # Web UI
      - "${MAILHOG_SMTP_PORT}:${MAILHOG_SMTP_PORT}" # SMTP
    networks:
      - public-services

  mysql:
    image: "mysql:${MYSQL_VERSION}"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 2s
      timeout: 3s
      retries: 30
    networks:
      - public-services

  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:${NGINX_PROXY_MANAGER_VERSION}"
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx-proxy-manager-data:/data
      - nginx-proxy-manager-letsencrypt:/etc/letsencrypt
    networks:
      - public-services

  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./docker/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 2s
      timeout: 3s
      retries: 30
    networks:
      - public-services

  redis:
    image: "redis:${REDIS_VERSION}"
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data
    networks:
      - public-services

  redis-commander:
    image: "rediscommander/redis-commander:${REDIS_COMMANDER_VERSION}"
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT}
    ports:
      - "${REDIS_COMMANDER_PORT}:${REDIS_COMMANDER_PORT}"
    depends_on:
      - redis
    networks:
      - public-services

volumes:
  portainer-data:
  grafana-data:
  prometheus-data:
  nginx-proxy-manager-data:
  nginx-proxy-manager-letsencrypt:
  mysql-data:
  postgres-data:
  redis-data:

networks:
  public-services:
    name: public-services