CREATE DATABASE IF NOT EXISTS db_bloom;
CREATE DATABASE IF NOT EXISTS db_gerbtuve;
CREATE DATABASE IF NOT EXISTS db_scclogi;

CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON db_bloom.* TO '${DB_USER}'@'%';
GRANT ALL PRIVILEGES ON db_gerbtuve.* TO '${DB_USER}'@'%';
GRANT ALL PRIVILEGES ON db_scclogi.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;